Repository adempiere/LVE, pull requests merged in 2020-05, with the labels that each got.

#19 Remove unused BankClientNo
  human_resource/src/main/java/base/org/erpya/lve/bank/exp/BNCNomina.java
Labels: Finanzas, Talento Humano

#20 Se cambia el salto de linea
  human_resource/src/main/java/base/org/erpya/lve/bank/exp/BNCNomina.java
Labels: Finanzas

#21 Change validation in TaxID
  core/src/main/java/base/org/erpya/lve/model/LVE.java
Labels: bug
